### ISSUE TITLE
Check emissions factors against time series

### ISSUE THREAD

**Issue by iisabeller** [NREL/EnergyIntensityIndicators#19]
Compare EIA time series against EPA emissions factors

- [x] Calculate implicit emissions factors, how does it change over time?
- [ ] Plot calculated emissions time series against EIA time series

**Comment by calmc** [comment]
@iisabeller I'm considering closing this, given our discussions on emission factors. I think we've concluded that
1. Carbon emission factor of electricity generation (kg CO2/kWh) for a given generation region has changed over time due to changes in generation mix
2.  Carbon emission factors of individual fuels (e.g., natural gas, diesel, anthracite coal) have not appreciably changed over time. So, we can use EPA standard emission factors for these fuels.

Anything else to document here?
